The Inspector (GNU Radio module gr-inspector): gr::inspector::signal_separator_c_impl Class Reference
gr::inspector::signal_separator_c_impl Class Reference
#include <signal_separator_c_impl.h>
Public Member Functions
signal_separator_c_impl (double samp_rate, int window, float trans_width, float oversampling, bool taps_file, std::map< float, std::vector< float > > &file_path)
~signal_separator_c_impl ()
void free_allocation ()
void build_filter (unsigned int signal)
void rebuild_all_filters ()
void apply_filter (int i)
void handle_msg (pmt::pmt_t msg)
pmt::pmt_t pack_message ()
void unpack_message (pmt::pmt_t msg)
void forecast (int noutput_items, gr_vector_int &ninput_items_required)
int general_work (int noutput_items, gr_vector_int &ninput_items, gr_vector_const_void_star &input_items, gr_vector_void_star &output_items)
double samp_rate () const
void set_samp_rate (double d_samp_rate)
filter::firdes::win_type window () const
void set_window (int d_window)
float trans_width () const
void set_trans_width (float d_trans_width)
int oversampling () const
void set_oversampling (float d_oversampling)
Additional Inherited Members
Public Types inherited from gr::inspector::signal_separator_c
typedef boost::shared_ptr< signal_separator_c > sptr
Static Public Member Functions inherited from gr::inspector::signal_separator_c
static sptr make (double samp_rate, int window, float trans_width, float oversampling, bool taps_file, std::map< float, std::vector< float > > &file_path)
Return new instance of Signal Separator block.
Constructor & Destructor Documentation
gr::inspector::signal_separator_c_impl::signal_separator_c_impl (double samp_rate, int window, float trans_width, float oversampling, bool taps_file, std::map< float, std::vector< float > > & file_path)
gr::inspector::signal_separator_c_impl::~signal_separator_c_impl ()
Member Function Documentation
void gr::inspector::signal_separator_c_impl::apply_filter (int i)
void gr::inspector::signal_separator_c_impl::build_filter (unsigned int signal)
void gr::inspector::signal_separator_c_impl::forecast (int noutput_items, gr_vector_int & ninput_items_required)
void gr::inspector::signal_separator_c_impl::free_allocation ()
int gr::inspector::signal_separator_c_impl::general_work (int noutput_items, gr_vector_int & ninput_items, gr_vector_const_void_star & input_items, gr_vector_void_star & output_items)
void gr::inspector::signal_separator_c_impl::handle_msg (pmt::pmt_t msg)
int gr::inspector::signal_separator_c_impl::oversampling () const inline
pmt::pmt_t gr::inspector::signal_separator_c_impl::pack_message ()
void gr::inspector::signal_separator_c_impl::rebuild_all_filters ()
Referenced by set_oversampling(), set_samp_rate(), and set_window().
double gr::inspector::signal_separator_c_impl::samp_rate () const inline
void gr::inspector::signal_separator_c_impl::set_oversampling (float d_oversampling) inline virtual
Implements gr::inspector::signal_separator_c.
References rebuild_all_filters().
void gr::inspector::signal_separator_c_impl::set_samp_rate (double d_samp_rate) inline virtual
Implements gr::inspector::signal_separator_c.
References rebuild_all_filters().
void gr::inspector::signal_separator_c_impl::set_trans_width (float d_trans_width) inline virtual
Implements gr::inspector::signal_separator_c.
void gr::inspector::signal_separator_c_impl::set_window (int d_window) inline virtual
Takes integers and does internal cast to firdes::win_type
Implements gr::inspector::signal_separator_c.
References rebuild_all_filters().
float gr::inspector::signal_separator_c_impl::trans_width () const inline
void gr::inspector::signal_separator_c_impl::unpack_message (pmt::pmt_t msg)
filter::firdes::win_type gr::inspector::signal_separator_c_impl::window () const inline
The documentation for this class was generated from the following file:
signal_separator_c_impl.h