The Inspector (GNU Radio module gr-inspector): gr::inspector::signal_detector_cvf_impl Class Reference
gr::inspector::signal_detector_cvf_impl Class Reference
#include <signal_detector_cvf_impl.h>
Public Member Functions
signal_detector_cvf_impl (double samp_rate, int fft_len, int window_type, float threshold, float sensitivity, bool auto_threshold, float average, float quantization, float min_bw, const char *filename)
~signal_detector_cvf_impl ()
void build_window ()
std::vector< float > build_freq ()
void build_threshold ()
std::vector< std::vector< unsigned int > > find_signal_edges ()
pmt::pmt_t pack_message ()
bool compare_signal_edges (std::vector< std::vector< float >> *edges)
void periodogram (float *pxx, const gr_complex *signal)
int work (int noutput_items, gr_vector_const_void_star &input_items, gr_vector_void_star &output_items)
void set_samp_rate (double d_samp_rate)
void set_fft_len (int fft_len)
void set_window_type (int d_window)
void set_threshold (float d_threshold)
void set_sensitivity (float d_sensitivity)
void set_auto_threshold (bool d_auto_threshold)
void set_average (float d_average)
void set_quantization (float d_quantization)
Additional Inherited Members
Public Types inherited from gr::inspector::signal_detector_cvf
typedef boost::shared_ptr< signal_detector_cvf > sptr
Static Public Member Functions inherited from gr::inspector::signal_detector_cvf
static sptr make (double samp_rate, int fft_len=1024, int window_type=0, float threshold=0.7, float sensitivity=0.2, bool auto_threshold=true, float average=0.8, float quantization=0.01, float min_bw=0.0, const char *filename="")
Return a signal detector block instance.
Constructor & Destructor Documentation
signal_detector_cvf_impl()
gr::inspector::signal_detector_cvf_impl::signal_detector_cvf_impl (double samp_rate, int fft_len, int window_type, float threshold, float sensitivity, bool auto_threshold, float average, float quantization, float min_bw, const char * filename)
~signal_detector_cvf_impl()
gr::inspector::signal_detector_cvf_impl::~signal_detector_cvf_impl ()
Member Function Documentation
build_freq()
std::vector<float> gr::inspector::signal_detector_cvf_impl::build_freq ()
build_threshold()
void gr::inspector::signal_detector_cvf_impl::build_threshold ()
build_window()
void gr::inspector::signal_detector_cvf_impl::build_window ()
compare_signal_edges()
bool gr::inspector::signal_detector_cvf_impl::compare_signal_edges (std::vector< std::vector< float >> * edges)
find_signal_edges()
std::vector<std::vector<unsigned int> > gr::inspector::signal_detector_cvf_impl::find_signal_edges ()
pack_message()
pmt::pmt_t gr::inspector::signal_detector_cvf_impl::pack_message ()
periodogram()
void gr::inspector::signal_detector_cvf_impl::periodogram (float * pxx, const gr_complex * signal)
set_auto_threshold()
void gr::inspector::signal_detector_cvf_impl::set_auto_threshold (bool d_auto_threshold) inline virtual
Implements gr::inspector::signal_detector_cvf.
set_average()
void gr::inspector::signal_detector_cvf_impl::set_average (float d_average) inline virtual
Implements gr::inspector::signal_detector_cvf.
set_fft_len()
void gr::inspector::signal_detector_cvf_impl::set_fft_len (int fft_len) virtual
Implements gr::inspector::signal_detector_cvf.
Referenced by set_samp_rate().
set_quantization()
void gr::inspector::signal_detector_cvf_impl::set_quantization (float d_quantization) inline
set_samp_rate()
void gr::inspector::signal_detector_cvf_impl::set_samp_rate (double d_samp_rate) inline virtual
Implements gr::inspector::signal_detector_cvf.
References set_fft_len(), and set_window_type().
set_sensitivity()
void gr::inspector::signal_detector_cvf_impl::set_sensitivity (float d_sensitivity) inline virtual
Implements gr::inspector::signal_detector_cvf.
set_threshold()
void gr::inspector::signal_detector_cvf_impl::set_threshold (float d_threshold) inline virtual
Implements gr::inspector::signal_detector_cvf.
set_window_type()
void gr::inspector::signal_detector_cvf_impl::set_window_type (int d_window) virtual
Takes integers and does internal cast to firdes::win_type
Implements gr::inspector::signal_detector_cvf.
Referenced by set_samp_rate().
work()
int gr::inspector::signal_detector_cvf_impl::work (int noutput_items, gr_vector_const_void_star & input_items, gr_vector_void_star & output_items)
The documentation for this class was generated from the following file:
signal_detector_cvf_impl.h