/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_synchronizer_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b7db46b2a5b6e60d5006115cbbffd512)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/inspector/ofdm_synchronizer_cc.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_synchronizer_cc_pydoc.h>

void bind_ofdm_synchronizer_cc(py::module& m)
{

    using ofdm_synchronizer_cc    = ::gr::inspector::ofdm_synchronizer_cc;


    py::class_<ofdm_synchronizer_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ofdm_synchronizer_cc>>(m, "ofdm_synchronizer_cc", D(ofdm_synchronizer_cc))

        .def(py::init(&ofdm_synchronizer_cc::make),
           py::arg("min_items"),
           D(ofdm_synchronizer_cc,make)
        )
        



        ;




}








