/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ofdm_zkf_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0b8212bf272cca3b8fa21cf118cc7953)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/inspector/ofdm_zkf_c.h>
// pydoc.h is automatically generated in the build directory
#include <ofdm_zkf_c_pydoc.h>

void bind_ofdm_zkf_c(py::module& m)
{

    using ofdm_zkf_c    = ::gr::inspector::ofdm_zkf_c;


    py::class_<ofdm_zkf_c, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ofdm_zkf_c>>(m, "ofdm_zkf_c", D(ofdm_zkf_c))

        .def(py::init(&ofdm_zkf_c::make),
           py::arg("samp_rate"),
           py::arg("signal"),
           py::arg("min_items"),
           py::arg("typ_len"),
           py::arg("typ_cp"),
           D(ofdm_zkf_c,make)
        )
        




        
        .def("set_samp_rate",&ofdm_zkf_c::set_samp_rate,       
            py::arg("d_samp_rate"),
            D(ofdm_zkf_c,set_samp_rate)
        )

        ;




}








